# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5129bebc827200acebbd1fe7c4b5d9730138637e321a547108a69feb10f48d62395645e6d45a08086c427b3afdb0e1930e7a36e1ba4674e6efd94231c9b333c

test:
  secret_key_base: e3cf43ca7df307f8f67ab1eb7c2df8c79030369269804af4ecb1547b8b5c21ea3fd6e84aae6aefcf1e552836f34066a2149b8439d2630b4137ffa40bd925700d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
